[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn reservations_service.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120"

[variables]
PYTHONUNBUFFERED = "1"
